# Generated by Django 6.0.4 on 2026-05-22 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('num_tickets', models.IntegerField(default=1)),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=46.02, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_top_city', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('CLASSIC', 'Classic Rows'), ('CLASSIC_PLUS', 'Classic Plus Rows'), ('PRIME', 'Prime Rows'), ('RECLINER', 'Recliner Rows')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
                ('banner', models.URLField(blank=True, max_length=500, null=True)),
                ('runtime', models.CharField(help_text='e.g., 2h 30m', max_length=20)),
                ('genres', models.CharField(help_text='Comma separated genres', max_length=200)),
                ('language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada')], max_length=20)),
                ('format_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('EPIQ', 'EPIQ'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=20)),
                ('release_date', models.DateField()),
                ('rating', models.CharField(default='UA', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cast', models.TextField(blank=True, help_text='Comma separated cast names')),
                ('director', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('cities', models.ManyToManyField(blank=True, related_name='movies', to='movies.city')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='movies.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='movies.seat'),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_classic', models.DecimalField(decimal_places=2, default=220.34, max_digits=8)),
                ('price_classic_plus', models.DecimalField(decimal_places=2, default=237.28, max_digits=8)),
                ('price_prime', models.DecimalField(decimal_places=2, default=262.7, max_digits=8)),
                ('price_recliner', models.DecimalField(decimal_places=2, default=440.68, max_digits=8)),
                ('screen_type', models.CharField(default='LASER', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.show'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.show'),
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('screen_count', models.IntegerField(default=1)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatres', to='movies.city')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theatre'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('show', 'row', 'number')},
        ),
    ]
